//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Brazilian.Information.Places {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DadosMunicipios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DadosMunicipios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(typeof(DadosMunicipios));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11	00015	Alta Floresta D&apos;Oeste
        ///11	00379	Alto Alegre dos Parecis
        ///11	00403	Alto Paraíso
        ///11	00346	Alvorada D&apos;Oeste
        ///11	00023	Ariquemes
        ///11	00452	Buritis
        ///11	00031	Cabixi
        ///11	00601	Cacaulândia
        ///11	00049	Cacoal
        ///11	00700	Campo Novo de Rondônia
        ///11	00809	Candeias do Jamari
        ///11	00908	Castanheiras
        ///11	00056	Cerejeiras
        ///11	00924	Chupinguaia
        ///11	00064	Colorado do Oeste
        ///11	00072	Corumbiara
        ///11	00080	Costa Marques
        ///11	00940	Cujubim
        ///11	00098	Espigão D&apos;Oeste
        ///11	01005	Governador Jorge Teixeira
        ///11	00106	Guajará-Miri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Municipios {
            get {
                return ResourceManager.GetString("Municipios", resourceCulture);
            }
        }
    }
}
