//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Brazilian.Exemplos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Externos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Externos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple.Brazilian.Exemplos.Externos", typeof(Externos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brasil (localmente /bɾaˈziw/[b]), oficialmente República Federativa do Brasil (Loudspeaker.svg? escutar),[9] é o maior país da América do Sul e da região da América Latina, sendo o quinto maior do mundo em área territorial (equivalente a 47,3% do território sul-americano)[2] e sexto em população[10][11] (com mais de 210 milhões de habitantes). É o único país na América onde se fala majoritariamente a língua portuguesa e o maior país lusófono do planeta,[12] além de ser uma das nações mais multiculturais e e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string acentos_wikipedia_original {
            get {
                return ResourceManager.GetString("acentos_wikipedia_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brasil (localmente /b?a?ziw/[b]), oficialmente Republica Federativa do Brasil (Loudspeaker.svg? escutar),[9] e o maior pais da America do Sul e da regiao da America Latina, sendo o quinto maior do mundo em area territorial (equivalente a 47,3% do territorio sul-americano)[2] e sexto em populacao[10][11] (com mais de 210 milhoes de habitantes). E o unico pais na America onde se fala majoritariamente a lingua portuguesa e o maior pais lusofono do planeta,[12] alem de ser uma das nacoes mais multiculturais e e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string acentos_wikipedia_semAcentos {
            get {
                return ResourceManager.GetString("acentos_wikipedia_semAcentos", resourceCulture);
            }
        }
    }
}
